"""Build version-checked spoken names from saved game rows and our own glossary."""
import base64
import gzip
import hashlib
import json
from pathlib import Path
import re

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]


def build(sources, glossary):
    result = {}
    for table, rows in sources.items():
        result[table] = {}
        for row, english in rows.items():
            russian = glossary.get(english)
            if not russian or not re.search("[А-Яа-яЁё]", russian):
                raise ValueError(f"Missing name: {table}/{row}: {english}")
            result[table][row] = [base64.b64encode(value.encode("utf-8")).decode("ascii")
                                  for value in (english, russian)]
    return result


if __name__ == "__main__":
    sources = json.loads((HERE / "action-name-sources.json").read_text(encoding="utf-8"))
    glossary = json.loads((HERE / "action-name-translations.json").read_text(encoding="utf-8"))
    catalog = build(sources, glossary)
    # Kept as a regression fixture for the original 124 names. The production
    # resource is generated by generate_game_text.py and includes other tables.
    output = ROOT / ".local/RussianActionNames-legacy.json.gz"
    output.parent.mkdir(parents=True,exist_ok=True)
    output.write_bytes(gzip.compress(json.dumps(catalog, separators=(",", ":"), sort_keys=True).encode("utf-8"), mtime=0))
    report = {"game_version": "2026.09.15.0000.0000", "catalog_sha256": hashlib.sha256(output.read_bytes()).hexdigest(),
              "source_sha256": hashlib.sha256((HERE / "action-name-sources.json").read_bytes()).hexdigest(),
              "glossary_sha256": hashlib.sha256((HERE / "action-name-translations.json").read_bytes()).hexdigest(),
              "unique_names": len({x for rows in sources.values() for x in rows.values()}),
              "rows": {table: len(rows) for table, rows in catalog.items()}}
    (ROOT / ".local/russian-action-names-legacy-coverage.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(report))
